# Generated by Django 4.1 on 2022-08-31 19:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_snippet_author_snippet_parent_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='users',
            field=models.ManyToManyField(related_name='snippets', to=settings.AUTH_USER_MODEL),
        ),
    ]
